# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

dist: trusty

matrix:
    # Note coverage is run in only one configuration.  Longest build first.
    include:
        - os: osx
          env: PYTHON=3.6
        - env: PYTHON=3.6
        - env: PYTHON=3.5 RUN_COVERAGE=yes
        - env: PYTHON=3.4
        - env: PYTHON=2.7
        - env: PYTHON=pypy

before_install:
    - export CONDA_ENV=travisci
    - buildscripts/incremental/install_miniconda.sh
    - export PATH=$HOME/miniconda3/bin:$PATH
    - buildscripts/incremental/setup_conda_environment.sh

install:
    - buildscripts/incremental/build.sh

script:
    - buildscripts/incremental/test.sh

after_success:
    - buildscripts/incremental/after_success.sh

notifications:
    email: false
    on_success: "change"
    on_failure: "always" # "change"
    slack:
        secure: "FKl89SqORRj0CQCeZZ6vLzSyX8644b+c3VMO2lfTMDj5asnSYmq4J8cmytzLuTO4vCDXXNzqbO+8jCsPtnt+2gvXC+NccZOvlPsHXOy9Iu4SAfPKmN2rsxlu27Tn86HN5zgGJsm53aQFG2BXnsc848/HtSzzxdUx8oml6w3SdwI="
