# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

dist: trusty

matrix:
    # Note coverage is run in only one configuration.  Longest build first.
    include:
        - env: PYTHON=3.5 RUN_COVERAGE=yes
        - env: PYTHON=3.4
        - env: PYTHON=2.7

before_install:
    # Add gcc for newer libstdc++ version (compatible with llvmdev builds)
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qy g++-4.9

    - export CONDA_ENV=travisci
    - buildscripts/incremental/install_miniconda.sh
    - export PATH=$HOME/miniconda3/bin:$PATH
    - buildscripts/incremental/setup_conda_environment.sh

install:
    - buildscripts/incremental/build.sh

script:
    - buildscripts/incremental/test.sh

after_success:
    - if [ "$RUN_COVERAGE" == "yes" ]; then codecov; coveralls; fi

notifications:
    email: false
    flowdock: "cb7bc57e58b3d42f77685f93211c03ab"
    on_success: "change"
    on_failure: "always" # "change"
