# References https://gist.github.com/dan-blanchard/7045057
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
    # Install Miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - PY_MAJOR_MINOR=${TRAVIS_PYTHON_VERSION:0:3}
    # Setup environment
    - conda create -n travisci --yes python=$PY_MAJOR_MINOR
    - source activate travisci
    # Install llvmdev (separate channel, for now)
    - conda install --yes -c antoine llvmdev
    # Install unittest2 and argparse for Python 2.6
    - if [ $PY_MAJOR_MINOR == "2.6" ]; then conda install --yes unittest2 argparse; fi
    # Install enum34 for Python < 3.4
    - if [ $PY_MAJOR_MINOR \< "3.4" ]; then conda install --yes enum34; fi
    # We need this line to have g++ 4.8 available in apt
    # (Travis' default gcc version doesn't support C++11).
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    # Force g++ 4.8 to be the default version
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
    - python setup.py build

script:
    - python runtests.py

notifications:
  email: false
  flowdock: "cb7bc57e58b3d42f77685f93211c03ab"
  on_success: "change"
  on_failure: "always" # "change"
