# Reference:
# - https://github.com/pypa/python-manylinux-demo

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           ARCH=x64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           ARCH=x32
      

install:
    - docker pull $DOCKER_IMAGE

script:
    - ./buildscripts/manylinux1/docker_run_$ARCH.sh

notifications:
    email: false
    on_success: "change"
    on_failure: "always" # "change"
    slack:
        secure: "FKl89SqORRj0CQCeZZ6vLzSyX8644b+c3VMO2lfTMDj5asnSYmq4J8cmytzLuTO4vCDXXNzqbO+8jCsPtnt+2gvXC+NccZOvlPsHXOy9Iu4SAfPKmN2rsxlu27Tn86HN5zgGJsm53aQFG2BXnsc848/HtSzzxdUx8oml6w3SdwI="
