# Environment based on https://github.com/rmcgibbo/python-appveyor-conda-example

environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\conda-recipes\\appveyor\\run_with_env.cmd"

  matrix:
    # Since appveyor is quite slow, we only use a single configuration
    # and a subset of the test suite (see test_script below)
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

init:
  # Use AppVeyor's provided Miniconda: https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_ARCH%" == "64" set MINICONDA=C:\Miniconda35-x64
  - if "%PYTHON_ARCH%" == "32" set MINICONDA=C:\Miniconda35
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

install:
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info
  - conda list
  - conda config --add channels numba
  - conda create -q -n testenv python=%PYTHON_VERSION% llvmdev="3.8.*"
  - call activate testenv

build: false

test_script:
  # Build and test the package
  - python setup.py build
  - python runtests.py -v
