# Configuration for codecov.io

foo:
    bar
comment:
    layout: "header, changes, diff"

status:
    project:
        # The build fails if total project coverage drops by more than 3%
        target: autoz
        threshold: 3z
    patch:
        enabled: no
