{% set shortversion = "10.0" %}
{% set version = "10.0.0" %}
{% set sha256_llvm = "df83a44b3a9a71029049ec101fb0077ecbbdf5fe41e395215025779099a98fdf" %}
{% set sha256_lld = "b9a0d7c576eeef05bc06d6e954938a01c5396cee1d1e985891e0b1cf16e3d708" %}
{% set build_number = "0" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
    fn: llvm-{{ version }}.src.tar.xz
    sha256: {{ sha256_llvm }}
    patches:
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   # [win]
    - ../partial-testing.patch
    # Intel SVML optimizations (two patches)
    # Latest versions from:
    # * https://github.com/conda-forge/llvmdev-feedstock/blob/c706309/recipe/patches/intel-D47188-svml-VF.patch
    # * https://github.com/conda-forge/llvmdev-feedstock/blob/c706309/recipe/patches/expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch
    - ../intel-D47188-svml-VF.patch
    - ../expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch
    # Reverts a patch limiting non-GlobalValue name length
    - ../0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    # Reverts a patch that auto-upgrades NVVM atomic intrinsics to atomicrmw instructions that NVVM doesn't recognise
    - ../0001-Revert-NVPTX-Use-atomicrmw-fadd-instead-of-intrinsic.patch
    - ../0002-Revert-NVPTX-Remove-now-unused-atomic.load.add.f32-i.patch

  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lld-{{ version }}.src.tar.xz
    fn: lld-{{ version }}.src.tar.xz
    sha256: {{ sha256_lld }}
    folder: tools/lld

build:
  number: {{ build_number }}
  string: "manylinux1h{{ PKG_HASH }}"
  script_env:
    - CFLAGS
    - CXXFLAGS
    - PY_VCRUNTIME_REDIST
  ignore_run_exports:
    # Is static-linked
    - xar

requirements:
  build:
    - cmake
    # - make  # Unavailable in old miniconda
    # Needed to unpack the source tarball
    - m2w64-xz         # [py27 and win]
    # Needed to build LLVM
    - python >=3
test:
  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                   # [unix]

    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

    # LLD tests
    - ld.lld --version                                       # [unix]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
