{% set shortversion = "9.0" %}
{% set version = "9.0.0" %}
{% set sha256_llvm = "8872be1b12c61450cacc82b3d153eab02be2546ef34fa3580ed14137bb26224c" %}
{% set sha256_lld = "9caec8ec922e32ffa130f0fb08e4c5a242d7e68ce757631e425e9eba2e1a6e37" %}
{% set build_number = "0" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  - url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
    fn: llvm-{{ version }}.src.tar.xz
    sha256: {{ sha256_llvm }}
    patches:
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - ../llvm-lto-static.patch   # [win]
    - ../partial-testing.patch
    # Intel SVML optimizations
    # The second part of this patch was published as:
    # https://reviews.llvm.org/D53035
    # (the first, as mentioned in the patch itself, was:
    # https://reviews.llvm.org/D47188)
    - ../D47188-svml-VF.patch
    # Reverts a patch limiting non-GlobalValue name length
    - ../0001-Revert-Limit-size-of-non-GlobalValue-name.patch

  - url: http://releases.llvm.org/{{ version }}/lld-{{ version }}.src.tar.xz
    fn: lld-{{ version }}.src.tar.xz
    sha256: {{ sha256_lld }}
    folder: tools/lld

build:
  number: {{ build_number }}
  string: "manylinux1h{{ PKG_HASH }}"
  script_env:
    - CFLAGS
    - CXXFLAGS
    - PY_VCRUNTIME_REDIST
  ignore_run_exports:
    # Is static-linked
    - xar

requirements:
  build:
    - cmake
    # - make  # Unavailable in old miniconda
    # Needed to unpack the source tarball
    - m2w64-xz         # [py27 and win]
    # Needed to build LLVM
    - python >=3
test:
  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                   # [unix]

    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

    # LLD tests
    - ld.lld --version                                       # [unix]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
