# Numba/llvmlite stack needs an older compiler for backwards compatability.
c_compiler_version:         # [linux and x86_64]
  - 7.5                     # [linux and x86_64]

cxx_compiler_version:       # [linux and x86_64]
  - 7.5                     # [linux and x86_64]

fortran_compiler_version:   # [linux and x86_64]
  - 7.5                     # [linux and x86_64]
