# Numba/llvmlite stack needs an older compiler for backwards compatability.
c_compiler_version:         # [linux and (x86_64 or ppc64le)]
  - 7                       # [linux and (x86_64 or ppc64le)]

cxx_compiler_version:       # [linux and (x86_64 or ppc64le)]
  - 7                       # [linux and (x86_64 or ppc64le)]

fortran_compiler_version:   # [linux and (x86_64 or ppc64le)]
  - 7                       # [linux and (x86_64 or ppc64le)]
