package:
  name: llvmlite
  version: "0.1.dev3"

source:
  path: ../..
  #git_url: https://github.com/numba/llvmlite.git

build:
  number: 1

requirements:
  build:
    - python
      # On channel https://binstar.org/antoine/
    - llvmdev 3.5* [win]
    #- cmake          [win]
  run:
    - python
    - enum34         [py26 or py27 or py33]

test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
  imports:
    - llvmlite
    - llvmlite.binding

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
