package:
  name: llvmdev
  version: "3.6.1"

source:
  fn: llvm-3.6.1.src.tar.xz
  url: http://llvm.org/releases/3.6.1/llvm-3.6.1.src.tar.xz
  sha1: 01ecab99adc9030ee34e9a2e19e65dfe64e1affe
  patches:
    # From http://reviews.llvm.org/D6052
    - ../llvm-elf-relocation.patch

build:
  number: 2

requirements:
  build:
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [linux]
    - llc -version         [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.5.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
